### PR TITLE
feat: Sum of digits

### PR DESCRIPTION
**Pull request by aditi-138**
# Description
This java program calculates the sum of digits of the number given input by the user.It illustrates the use of looping concept in java and the method to extract digits from a number.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Added code.java to the project directory.

## How Has This Been Tested?
Tested on Java IDE, BlueJ. Produces expected output.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

## Screenshot

Screenshot (51)

### CODE REVIEW

**Comment by aditi-138** [comment]
Screenshot (51)

**Comment by Manaya20** [comment]
check pr description template, and make changes to it
make it more enhancing

**Comment by Manaya20** [comment]
other work gg

**Comment by sm-sami** [comment]
Update the pr description with SRMKZILLA's pr template

**Comment by Manaya20** [comment]
edit pr subtitle for screenshot

**Comment by Manaya20** [comment]
make it sub heading

**Pull request merged**
