### PR TITLE
feat: add hello.py

### PR DESCRIPTION
**Pull request by keftee**
# Description

## What?
I have added support for users to be able to print "hello -keftee".

## Why
This is a simple task assigned by SRMKZILLA to practice our PRs.

## How?
I implemented this feature using the print function.

## Testing
I have tested this implementation at least thrice now.

## Screenshot
Screenshot 2023-10-20 203828
### Output
Screenshot 2023-10-20 204112

### CODE REVIEW

**Comment by shawshankkumar** [comment]
add proper labels and assign yourself
image

and upload a dp on github :)

**Comment by keftee** [comment]
> add proper labels and assign yourself 
I cannot assign myself as I am not a collaborator. I don't have the option to. Can you help me with that?

**Comment by keftee** [comment]
I cannot add myself as I am not a collaborator. Can you help me with that?

**Comment by sm-sami** [comment]
@keftee format the code with a formatter, preferably with black for python

**Comment by keftee** [comment]
@sm-sami As you requested, I have added python formatting using black.

**Review by sm-sami — APPROVED** [review]
LGTM

**Pull request merged**
