### PR TITLE
feat: Add 'hello.py'

### PR DESCRIPTION
**Pull request by keftee**
This PR adds the file 'hello.py'.

### CODE REVIEW

**Comment by Manaya20** [comment]
good commit name and pr title

**Comment by Manaya20** [comment]
PR Description not at all apt, and following the convention

**Comment by AakashRawat04** [comment]
it's a common convention to use present tense in commit messages..
When writing a commit message for the addition of the "hello.py" file, you can use a present-tense message like:

"Add 'hello.py' file"

you can improve the PR title. good PR description

**Comment by sm-sami** [comment]
why is there a '' in the pr title? remake the pr with proper commit message

**Pull request closed without merging**
