### PR TITLE
Add new main.dart file

### PR DESCRIPTION
**Pull request by harishrsekar**
Added a new main.dart file to the forked repository

### CODE REVIEW

**Comment by utkarshini14** [comment]
edit and write a good pr description.

**Comment by utkarshini14** [comment]
also assign yourself and add me as reviewer

**Comment by AakashRawat04** [comment]
follow the commit convention 
reference: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by sm-sami** [comment]
Remake the PR with proper commit messages and description

**Pull request closed without merging**
