### PR TITLE
Add README file

### PR DESCRIPTION
**Pull request by vinay-04**
## Description:
Added a README file with the task and an example.

## Details:
It has title `KZILLA PR Task.`
Also added a logo of kzilla.

## Execution:
pr

## Checklist:
My code follows the guidelines of this project.
The code follows best practices and coding standards.
I have performed a self review of my own code.

### CODE REVIEW

**Comment by Manaya20** [comment]
good commit name

why no description is provided!??

**Comment by AakashRawat04** [comment]
nice commit message. try adding small PR description

**Comment by sm-sami** [comment]
Add a proper description and a screenshot as well

**Comment by sm-sami** [comment]
> Could elaborate on the screenshots?

Since you are adding a readme file (a type of file which can be rendered), show us the end result/output

**Pull request merged**
