### PR TITLE
Update sample.py

### PR DESCRIPTION
**Pull request by vijaybalamahalingam**
**Description:**
This pull request adds a feature: Subtraction performed.

**Details:**
Getting 1st input as "num1".
Getting 2nd input as "num2". 
And finally determining the "result" by subtracting them.

**Execution:**

pic

**Checklist:**
 My code follows the guidelines of this project.
 The code follows python best practices and coding standards.
 I have performed a self review of my own code.

### CODE REVIEW

**Comment by Manaya20** [comment]
make changes to the pr description, check template once and make changes

**Comment by Manaya20** [comment]
gg work on other things

**Comment by Manaya20** [comment]
assignee should be you, not us

**Comment by shawshankkumar** [comment]
commit names can be improved in the future

**Pull request merged**
